# Generated by Django 3.2 on 2021-04-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rentals',
            fields=[
                ('OrderId', models.IntegerField(primary_key=True, serialize=False)),
                ('RentalStart', models.DateField()),
                ('RentalEnd', models.DateField(max_length=20)),
            ],
        ),
    ]
