# Generated by Django 3.2 on 2021-04-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentals',
            name='RentalEnd',
            field=models.DateField(),
        ),
    ]
