# Generated by Django 3.0.5 on 2021-04-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0004_auto_20210428_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentals',
            name='OrderId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
