# Generated by Django 3.2 on 2021-04-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('MovieId', models.AutoField(primary_key=True, serialize=False)),
                ('MovieName', models.CharField(max_length=100)),
                ('MovieGenre', models.CharField(max_length=100)),
                ('MoviePrice', models.IntegerField(max_length=20)),
            ],
        ),
    ]
