# Generated by Django 3.0.5 on 2021-04-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='MovieId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
