# Generated by Django 3.0.5 on 2021-04-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_auto_20210428_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='MovieId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
